# Generated by Django 3.2.3 on 2021-05-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, default='no_pic.jpg', upload_to='reports'),
        ),
    ]
